spring.application.name=contentEngine
server.port= ${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d9h47on15fvs73cqgesg-a.frankfurt-postgres.render.com:5432/contentenginedb}
spring.datasource.username=${DB_USERNAME:contentenginedb_user}
spring.datasource.password=${DB_PASSWORD:I6lU34ZMyTLf7sxX3xmMvma46nWkztQ6}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=${GEMINI_API_KEY:your_gemini_api_key_here}